# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: EmployeeDatabase_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
pool:
  name: Default



variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
 

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    # Replace 'EmpDBScript' with your GitHub repository name
    git clone https://github.com/MullaAfiya/EmpDBScript.git
  displayName: 'Clone repository'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Assuming your SQL script is in the root of the repository
      Get-ChildItem -Recurse -Include *.sql | ForEach-Object { $_.FullName }
  displayName: 'List SQL scripts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
